### ISSUE TITLE
Research vendor applications: Primavera and Wrike

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#11]
**[EN]**  
Sign up in these applications:
1. Primavera
2. Wrike

and try using them and exploring their features. As you are using these pieces of software, try taking notes about their:
- UI
- UX
- Flows of Processes
- Systems (the app might be able to be broken in multiple logical parts: e.g. task management, messaging, financial features). Each application might have different systems and features e.g. In GitHub you can reference an `issue` or `pull request` or parts of codebase in a task which is not available in most other applications. 
- Features of each logical part (e.g. features available in task management)
- Terminology

---

**[FA]**
در برنامه‌های زیر ثبت نام کن:
1. Primavera
3. Wrike

و اونارو به عنوان کسی که میخواد پروژه رو مدیریت کنه استفاده کن تا بتونی امکاناتی که برنامه در اختیار مدیر پروژه قرار میده رو ببینی و اکتشاف کنی. سعی کن وقتی داری استفاده میکنی موارد زیر رو یادداشت کنی:
1. یو آی
4. یو ایکس
5. اینکه جریان کلی روندها توی برنامه چطوریه (مثلا ثبت نام کردی بعدش چی شد، یا پروژه ایجاد کردی بعدش چی شد)
6. سیستم‌های متفاوت رو تشخیص بده. اکثر برنامه‌هایی که مشخص شده، دارای بخش‌های متفاوتی هستن. مثلا ممکنه یکی مدیریت تسک + حسابداری + پیام‌رسانی داشته باشه، ممکنه یکی دیگه مدیریت تسک + مدیریت پروژه داشته باشه. هر تقسیم بندی‌ای که به نظرتون منطقی اومد رو بنویسید.
7. برای هر بخش که تو مورد قبلی مشخص کردیم باید تمام فیچرهاشو در بیاریم و مستند کنیم.
8. ترمینولوژی (واژگان مورد استفاده)

**Comment by prvsa2003** [comment]
# Primaver
Primavera is a project management program and I am tasked with reviewing this program from the perspective of UI, UX and app performance

# Setup APP
The installation process of this application is not very difficult, I think it is reasonable for an application. You can see the application installation steps below:

![setup_1](https://github.com/user-attachments/assets/8e264fc2-2658-4649-8967-f6577fa0a99a)

After launching all the packages and filling the package status and general status and displaying this message "Your requested operation has been successfully completed", we enter the next step of selecting "Database configuration":

![setup_2](https://github.com/user-attachments/assets/da310986-9bb4-4c12-816d-92048032440b)

In this session we should config database so we must select P6 Professional driver type so we select P6 Pro standardalone [SQLite]

![setup_3](https://github.com/user-attachments/assets/ec6e2e61-8723-40a7-82b7-5b7cb899a960)

After clicking next, if we have an standalone database to add connection to, click this option, but if we don't have an standalone database to connect to, we should to select this, so finally click next.   
In this sesion we should select a password for our standalone database . Pay attention that password and username is so importent , if we open  and log in to this application any time  , we must know username and password from us . 

![setup_4](https://github.com/user-attachments/assets/f4f06cb7-96ef-4405-980f-c15ad1504148) 

and in finally we should click on next and finish    
**congrajetion we could set up this application easly 🎉**

# My opinion about the installation
I think this program is set up logically and user-friendly, and my opinion about the user interface of this program is very old because of the use of old buttons. I think the material buttons could be better to used.

When you start the application , we have to enter the username and password every time, I think this is very good in terms of security.

# Menu Bar

![menu_bar](https://github.com/user-attachments/assets/1839492a-1945-4e86-8658-6f5407546a08)

In the menu bar of the file section, we can create a new project or open old projects or print a page and export from the project. This is a very good option that we can fully export in any format

In the Edit section, we can cut copy and paste. Most of the editing options can be done with keyboard combination keys. The only important option we have is user perfrences, which I will explain below.

In View we have display settings

The Project option is disabled because we don't have a project, when we create a project, the Project option is activated in the menu bar. 

The Enterprise settings related to different organizational levels, including different columns of the work breakdown structure, different levels of timing, different levels of benefits and roles, etc.

 The Tools related to scheduling and performs a series of reports at the end of the project

 The Admin is settings related to the currency settings system itself

![admin_prefrences](https://github.com/user-attachments/assets/1939abaf-8a39-4008-8784-82622de2500a)

From the Admin Preferences option, we can make system settings. In my opinion, it is very complete, but in terms of UI, it would be better if there was a save button instead of the cancel button

![user_prefrences](https://github.com/user-attachments/assets/13478950-b41e-449c-9967-6d40ef21bd57)

In user preferences, we will make settings related to the user . about Time Units section When we say 8 hours a day, the hour unit is determined in the units format section, and the day unit is determined in the duration format section.

In the currency section, we can choose our desired currency units, which are not available in this list of all currency units, but we can add our desired monetary unit from currency

![obs-chart](https://github.com/user-attachments/assets/3a8efa4b-5ed5-4d59-848a-e15822fdcf8e)

In this section, we can determine the chart related to the organizational chart. First, the UI does not look interesting, most of the buttons do not work properly and are disabled for no reason, which causes dissatisfaction and problems for the user.

Overall, this section has interesting options, but the main problem is that most of them are disabled for no reason

![eps_img](https://github.com/user-attachments/assets/b75d0db5-6fce-4806-b2fd-db7d302a92ee)

In this section, using eps settings, we define the types of projects that we manage.

Similar to the previous mode, it provides good features to the user, but most of the features either work slowly or are inactive, and this causes dissatisfaction of the user

![calender](https://github.com/user-attachments/assets/2b37c567-9c79-439f-be55-a6e9724b9954)

In this section, we can choose three types of calendars 
The global calendar is for when we want the calendar to be considered for both the resource and the project

In the resource type calendar, we determine what time frame the resources are available to us, and this time frame can be different for each resource.

From my point of view, the part of setting the table is not very interesting and it is not designed simply, it has some complexity that may be difficult for newbies

![Image](https://github.com/user-attachments/assets/4ee9ef45-f288-4214-9454-0286ddea9084)

In calendar weekly hours, we can determine the working hours in each week

In calendar weekly hours, we can determine the working hours in each week.   

 I think it would have been better to use appropriate animations to determine the hours, for example, instead of typing the hours, the same hours could have been displayed in a clock animation.

# WPS & Docs 
If we have appointments related to the project or documents, documents or anything important that we want to add to the project, we do it through WPS&docs.

![Image](https://github.com/user-attachments/assets/62575bba-7e2b-45dd-9d80-49f5a9c6170e)

The upper part is for adding a series of information and the lower part is for adding details

![Image](https://github.com/user-attachments/assets/73a5b56c-1c4d-4eb5-913f-e94b37a68813)

This left part is for adding or deleting or cutting documents


# General conclusion
In my opinion, in addition to the boring and old UI it has, overall it is a comprehensive software that can help us a lot in project management, and I think it lacks only one thing, and that is the interaction between team members in the program, a place to deploy. There is no interaction between members of a team, and in my opinion, it can be one of the weak points of this software.

## Terminology

WBS : 
A hierarchical arrangement of the products and services produced during and by a project. An element usually represents a deliverable, product or service and contains the activities needed to produce the deliverable. It enables division of a project into logical pieces for the purpose of planning and control.

OBS : 
The organizational breakdown structure (OBS) is a global hierarchy that represents the managers or positions responsible for the projects in your enterprise. The OBS usually reflects the management structure of your organization, from top-level personnel down through the various levels constituting your business. You can associate the responsible managers with their areas of the EPS —either nodes or individual projects. When you associate a responsible manager with an EPS node any projects you add to that branch of the EPS are assigned that manager element by default. The OBS hierarchy is also used to grant users specific access privileges to projects and the WBS levels within projects.

Currencies : 
You can specify the monetary unit or base currency used to store costs for all projects in the database, as well as the monetary unit or view currency used to display costs in windows and dialog boxes.
The exchange rate for the base currency is always 1.0. If you select a different currency than the base currency to view costs, the base currency value is multiplied times the current exchange rate for the view currency to calculate the values displayed in cost fields.
For example, if the base currency is U.S. Dollars, the view currency is Euros, and the exchange rate is €0.75 = $1, a value of $10 stored in the database is displayed as €7.5 in cost fields in windows and dialog boxes. Similarly, if you enter €7.5 in a cost field, it is stored in the database as $10.

Summarize : 
To summarize the projects in other nodes, select the respective node and choose Actions | Summarize Projects. In Primavera P6 EPPM summarizing projects is important, so that the EPS view displays the most up-to-date project data. Remember that the Summarize Projects process is not automatic

Filter : 
A filter temporarily limits the projects or activities that appear on screen, according to criteria you establish. One example, you can view active projects or activities scheduled to start during the next three weeks. You can apply one or more filters to the layout at any time.

Network Logic Diagram : 
A network logic diagram is a graphic representation of all the activities in a project and their logical (dependent) relationships.

Percent Complete Type : 
The way in which the percent complete for the selected activity is determined. An activity's percent complete type can be Units, Duration, or Physical.

Duration % Complete : 
When using Duration % Complete to update an activity the selected activity's Activity % Complete is tied to its Duration % Complete.

Units % Complete : 
When using Units % Complete to update an activity the selected activity's Activity % Complete is tied to its Units % Complete.

Physical % Complete : 

When using Physical % Complete you may enter the selected activity's Activity % Complete in the Physical % field on the Status tab. Physical percent complete is not connected directly to remaining duration.


Lag : 
Lag specifies an offset or delay between an activity and its successor. It can be added to any relationship type and can be positive or negative. There are four calendar types available for scheduling lag, the predecessor activity calendar, the successor activity calendar, the 24-hour calendar and the project default calendar.

Successor : 
An activity that must occur after another activity. An activity can have multiple successors, each with a different relationship to it.

Free Float : 
The amount of time an activity can be delayed from its Early Start without delaying the activities that immediately follow (successor activities).

Total Float : 
The amount of time an activity can be delayed from its Early Start without delaying the project. It is the difference between an activity’s late dates and early dates and is automatically calculated each time the project is scheduled.

Critical Path :
The critical path is a series of activities that determines a project's completion date.

**Comment by prvsa2003** [comment]
# wrike
Wrike is a powerful project management platform designed to help teams streamline their workflows, improve collaboration, and boost productivity. With features like task management, Gantt charts, customizable dashboards, time tracking, and file sharing, Wrike provides a centralized space for managing complex projects. It allows for real-time communication and updates, ensuring that teams stay aligned and meet deadlines efficiently. Integrations with popular tools such as Slack, Google Drive, and Microsoft Office enhance its functionality, making it a versatile solution for teams of all sizes. Wrike is ideal for businesses looking to improve project visibility and coordination.

## sign up 
At first, to sign up on the site, it asks for an email address, so we enter the email address

![sign_up](https://github.com/user-attachments/assets/fbd76c50-1de5-4c4c-9e0a-0adc4ce2155a)

Then, in the next step, it asks us for a name and the name of the company, which we enter

![sign_up2](https://github.com/user-attachments/assets/5145124a-aeb7-4f31-bf9f-545658af0cdf)

There is also an interesting section when sign up, it asks the number of employees of the company and the number of people who are going to work in wrike. I think this might be useful.

![sign_up3](https://github.com/user-attachments/assets/1fe5f29b-1c58-4867-8ed4-58adb7f538d7)

At this section , that asks the type of team and our task as something that has been assigned to us
![sign_up4](https://github.com/user-attachments/assets/e0f6ae9b-e15c-42ca-857a-ac28448ada16)

In this section, it asks for the name of the project we are going to manage and the working method

![Screenshot (4866)](https://github.com/user-attachments/assets/9708b973-9760-44bb-9bb6-845cfee453bb)

At this stage, we display the tasks based on the required items as we need, either in the form of a ganet diagram or in the form of a table or in the form of a board.

![Screenshot (4868)](https://github.com/user-attachments/assets/7d6335b3-ef92-4556-b1c6-395866ad2ac6)

During sign up on the site, there should have been a button to return to the previous section, but it is not there . 


## create project 
From the menu on the left side of the project and folders section, we can create a new project by clicking on the + button

![Screenshot (4882)](https://github.com/user-attachments/assets/a190a4b5-792d-4d32-baa8-1dc9cb260cb8)

![Screenshot (4883)](https://github.com/user-attachments/assets/88ae441c-db72-4f2a-9418-167bc73750e7)

![Screenshot (4887)](https://github.com/user-attachments/assets/9e41a188-2428-469e-8417-137da4cbdd4f)

By clicking on the item, a list of items will appear from which we can choose whether we want to create a task or a project or not or any item that appears in the list and it asks us for its name in addition to its type

![Screenshot (4890)](https://github.com/user-attachments/assets/bf38b1ef-4d9c-4ba1-936b-5fbcf65f4038)

## sub task in wrike 
By clicking on the three dots, there is an item that, if clicked, will display a list of sub items, that is, it is not just a sub task, it can also be used as a sub note.

![Screenshot (4892)](https://github.com/user-attachments/assets/77a403bc-aeaf-4e72-be2b-0d58d9350ec2)

## workload 
workload adjusts the workload and shows how much each team member has worked during the week, and based on this workload, tasks can be divided more appropriately.

![Image](https://github.com/user-attachments/assets/d6dcaec3-76af-4222-9ee3-332e341001a3)

![Image](https://github.com/user-attachments/assets/60cbfbb8-7291-4b75-b677-f01c4dc0760d)


## todo in wrike 
We have a todo section where we can manage our tasks, set the status, write a note, upload a file and leave a mention, and you can also send a message.

![Image](https://github.com/user-attachments/assets/de070f57-56fa-4b53-b129-91df5c12c879)

## request forms
From the request forms section, you can write a form for the incoming work requests of the team

![Image](https://github.com/user-attachments/assets/7fc76cb3-8fe9-4897-bcb0-bb1146c48c46)

## invite people 
From the invite section, you can invite other programmers or people to the team or company and send an invitation

![Image](https://github.com/user-attachments/assets/1930559d-a49c-4532-a8a6-afe349efa325)

![Image](https://github.com/user-attachments/assets/c089bf3c-0362-4189-921b-22d9e9c6d3ed)

![Image](https://github.com/user-attachments/assets/5de9d5a9-d494-4eab-9c0b-ead8b15e8957)

## reports 
In this section, an analysis panel and a customized report can be created
It is a good feature that the primavera application did not give the user the ability to deliver a customized report

![Image](https://github.com/user-attachments/assets/2eca3b90-56c8-41a0-aa73-ac5566d35ea8)


## shared with me 
The messages written for each task are displayed in the shared with me section
It is better to say that in addition to the message, everything that we share is shown in this section

![Image](https://github.com/user-attachments/assets/a0f6a2f7-4cef-48e4-bf36-0080d5019048)

## inbox 
In the inbox section, we have 3 sections: incoming, sent, and archive, which respectively show the messages sent to us, the messages we sent, and the archived messages

![Image](https://github.com/user-attachments/assets/2d1dd362-6510-4232-a52d-53777baeac6b)
![Image](https://github.com/user-attachments/assets/00bbfffe-29e5-45f5-a9a4-cae5b0ab5646)
![Image](https://github.com/user-attachments/assets/3cf61bf2-f33b-477e-9068-da14629c499d)

By hovering over each item in incoming, three modes are displayed, the rightmost mode is to mark it as unread, then the second mode is to archive the message, and the last and third mode is to silence or close the notifications of that message

![Image](https://github.com/user-attachments/assets/5f3c1611-7b8e-40d4-aecd-0ca2faaf614e)

## General opinion

In my opinion, both UI and UX are very attractive and useful, even more efficient than GitHub and Perimaver 
The terminology is not difficult and the different sections and items are almost clear and readable and you can understand what is waiting for us from the meaning of the word. As a test user who used this site, I was very satisfied. Compared to Primaver, it had a very good and interesting performance. It had a variety of options that open the user's hands to make more accurate choices and help a lot in managing projects for Any team can have it


## terminology 

1. Task
A task is the fundamental unit of work in Wrike. It can contain a description, due dates, assignees, attachments, and comments. Tasks are often grouped into folders or projects.

2. Folder
Folders are used to organize tasks. They can represent categories, departments, or any other grouping logic. Folders can be nested, and tasks can be tagged in multiple folders.

3. Project
Projects in Wrike are a collection of tasks and subtasks aimed at achieving a specific goal. Each project can have its own start and end date, status, and owner.

4. Space
A Space is a larger organizational structure in Wrike that contains projects, folders, and tasks. Spaces are usually used to organize work by department, team, or business unit.

5. Blueprints
Blueprints are reusable templates for projects, folders, and tasks. They help standardize repetitive work, making it easier to start new projects or tasks.

6. Request Forms
These are customizable forms used to collect information from internal or external users. Requests submitted through these forms can automatically generate tasks or projects.

7. Dashboard
Dashboards in Wrike provide a visual overview of tasks and projects. They can include widgets to display tasks based on criteria such as due date, assignee, or status.

8. Report
Reports in Wrike allow users to track progress across tasks, projects, and folders. Reports can be customized to display data such as task status, project completion, and more.

9. Stream
The stream is a real-time activity feed that shows updates, comments, and changes to tasks and projects, helping teams stay informed on ongoing activities.

10. Dependencies
Dependencies link tasks to indicate a relationship between them. For example, one task might need to be completed before another can start (Finish to Start dependency).

11. Subtask
A subtask is a task nested within a parent task. Subtasks help break down complex tasks into smaller, manageable actions.

12. Gantt Chart
Wrike’s Gantt Chart is a visual timeline that shows how tasks are scheduled and the relationships between them (e.g., dependencies). It's a tool used for project scheduling and planning.

13. Assignee
An assignee is a person responsible for completing a task. Multiple users can be assigned to a task.

14. Time Tracker
Wrike’s time tracking feature allows users to log the time they spend on individual tasks, helping with project management and billing.

15. Custom Fields
Custom fields are additional fields that can be added to tasks, folders, or projects to capture specific information, such as budget, priority, or other data points relevant to a team.

16. Approval
The approval feature allows users to submit tasks, projects, or documents for approval. Approvers can then provide feedback, approve, or reject the work.

17. Automation
Automation rules can be set up to automate repetitive tasks or workflows, such as changing task statuses or assigning tasks based on certain triggers.

18. User Types
Wrike users have different roles and permissions. Common user types include:
Regular Users: Full access to tasks, projects, and folders.
Collaborators: Limited access, usually for commenting and viewing.
External Users: Users from outside your organization with restricted access.

19. Table View
This is a spreadsheet-like view of tasks that displays details in rows and columns. It’s useful for organizing and filtering tasks based on specific criteria.

20. Workflows
A workflow in Wrike is a custom sequence of task statuses that reflect your team's specific processes. For example, a marketing team may use a workflow with statuses like "In Review" or "Published."
