### ISSUE TITLE
Research vendor applications: Mizito and SmartSheet

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#12]
**[EN]**  
Sign up in these applications:
1. Mizito
2. SmartSheet

and try using them and exploring their features. As you are using these pieces of software, try taking notes about their:
- UI
- UX
- Flows of Processes
- Systems (the app might be able to be broken in multiple logical parts: e.g. task management, messaging, financial features). Each application might have different systems and features e.g. In GitHub you can reference an `issue` or `pull request` or parts of codebase in a task which is not available in most other applications. 
- Features of each logical part (e.g. features available in task management)
- Terminology

---

**[FA]**
در برنامه‌های زیر ثبت نام کن:
1. Mizito
3. SmartSheet

و اونارو به عنوان کسی که میخواد پروژه رو مدیریت کنه استفاده کن تا بتونی امکاناتی که برنامه در اختیار مدیر پروژه قرار میده رو ببینی و اکتشاف کنی. سعی کن وقتی داری استفاده میکنی موارد زیر رو یادداشت کنی:
1. یو آی
4. یو ایکس
5. اینکه جریان کلی روندها توی برنامه چطوریه (مثلا ثبت نام کردی بعدش چی شد، یا پروژه ایجاد کردی بعدش چی شد)
6. سیستم‌های متفاوت رو تشخیص بده. اکثر برنامه‌هایی که مشخص شده، دارای بخش‌های متفاوتی هستن. مثلا ممکنه یکی مدیریت تسک + حسابداری + پیام‌رسانی داشته باشه، ممکنه یکی دیگه مدیریت تسک + مدیریت پروژه داشته باشه. هر تقسیم بندی‌ای که به نظرتون منطقی اومد رو بنویسید.
7. برای هر بخش که تو مورد قبلی مشخص کردیم باید تمام فیچرهاشو در بیاریم و مستند کنیم.
8. ترمینولوژی (واژگان مورد استفاده)

**Comment by hossiiiw** [comment]
#میزیتو
#Mizito 
___
#####میزیتو ابزار مدیریت برنامه است که توسط برنامه نویسان ایرانی طراحی و پیاده سازی شده است که من در این بخش به بررسی ویژگی #####ها و امکانات ان می پردازم 
#####Mizito is a program management tool designed and implemented by Iranian programmers. In this section, I will review 
#####its features and capabilities.
____
#ورود و ثبت نام
#Login and  Signup
___
در ابتدا برای ثبت نام باید شماره موبایل را وارده کرده سپس پس از دریافت کد تایید ان را وارد میکنیم سپس اطلاعات اولیه مانند نام نام خانوادگی رمز عبور و نام شرکت یا تیم را وارد میکنیم و با تکمیل این اطلاعات ثبت نام با انجام می شود
First, to register, you must enter the mobile number, then after receiving the confirmation code, enter it, then enter the 
basic information such as the name, username, password, and the name of the company or team, and by completing this 
information, the registration is done.
####مرحله اول 
####first step
![Screenshot 2024-09-24 152058](https://github.com/user-attachments/assets/53d8a0ae-2f71-414a-9699-c17fa636cac8)

####مرحله دوم
####second step
![Screenshot 2024-09-24 152410](https://github.com/user-attachments/assets/a52521f7-5105-445a-ba4a-6a5f3242242d)

####مرحله سوم
####thir step
![Screenshot 2024-09-24 152603](https://github.com/user-attachments/assets/efe4a8da-f651-4d2b-aadd-afd0d85c66af)

####ثبت نام به پایان رسید و وارد پنل شدید
####Registration is finished and you have entered the panel
 
___
#رابط کاربری
#UI

از لحاظ رابط کاربری از نظر من  بخش صفحه ورود و ثبت نام که از انیمیشن استفاده شده خیلی جذابه ولی رنگ هایی که توی محیط کلی استفاده شده که رنگ قرمز روشن یا یکم مایل به رنگ نارنجی است جذابیت خاصی برای من نداشت چون از این نوع رنگ ها برای فروش محصولات یا نرم افزار های فروشگاهیی استفاده میشه ولی در این نوع سایت ها که بیشتر کاربر ها برنامه نویس هستند و معمولا نیز برنامه نویس ها یا مهندسان کامپیوتر از رنک های دارک خوششون میاد استفاده میشد خیلی بهتر بود 
In terms of the user interface, in my opinion, the part of the login and registration page that uses animation is very 
attractive, but the colors used in the general environment, which are bright red or slightly orange, were not particularly 
attractive to me because of this type of color  are used to sell products or store sites, but in these types of sites where
 most of 
the users are programmers and usually programmers or computer engineers like dark ranks, it was much better.

___
#تجربه کاربری
#UX

از لحاظ تجربه کاربری نیز به نظر با وجود این تو رنگ ها خیلی جالب به نظر نمی رسه چون این نوع نرم افزار ها بیشتر با برنامه نویسا و مهندسان کامپیوتر سر و کار دارند این نوع رنک ها خسته کننده هستند و حتی میتونست یک بخشی برای شخصی سازی ایجاد میکردند که میتونستیم رنگ و تم رو شخصی سازی کنیم یک مورد دیگه ای که از نظر من خیلی خیلی مهمه عدم وجود دکمه تغییر مود سایت به دارک یا روشن که نداره و این خیلی بده و  برخی ایکون ها و قسمت های سایت یک سایه کوچیکی دارند که در دارک مود خیلی به چشم میومد و ظاهر سایت رو خیلی بهتر میکرد که متاسفانه در این مود حالت اولیه خیلی معلوم نیست 

n terms of user experience, despite this, the colors do not seem very interesting, because these types of software mostly deal with programmers and computer engineers, these types of colors are boring, and it could even be a section for personal use. They created a system that we could customize the color and theme. Another thing that is very, very important in my opinion is the lack of a button to change the site mode to dark or light, which is very bad, and some icons and parts of the site have a small shadow. They say that it is very visible in dark mode and it would improve the appearance of the site, which
 unfortunately is not very clear in this mode.


ایجاد تسک یا وظیفه خیلی ساده و راحته و موقع ایجاد تسک عناوینی همچون عنوان تسک یا وظیفه، توضیحات در مورد تسک، اضافه کردن برچست(تگ)،اضافه کردن چک لیست، اضافه کردن تایم یادآوری که ویژگی خوبیه ، اساین یا دادن یک تسک به یک فرد و انتخاب دسته بندی پروژه
Creating a task or task is very simple and easy, and when creating a task, titles such as the title of the task or task, description of the task, adding a check (tag), adding a checklist, adding a reminder time, which is a good feature, assigning or giving a task to A person and choose a project category
![Screenshot 2024-09-24 160410](https://github.com/user-attachments/assets/2ed5a462-8e35-42d9-bfc4-1e2c0339f908)
 ___

#امکانات
#Features

***
***
بخش تنظیمات شخصی که به 3 قسمت تقیسیم بندی شده است:
1-عمومی
2-امنیت
3-نوتیفیکیش یا ایمیل
The personal settings section is divided into 3 parts:
1-General
2- Security
3- Notification or email
![Screenshot 2024-09-24 164557](https://github.com/user-attachments/assets/b7f105d4-c7d6-44ba-90a6-cd8ff5d4dfc9)
در بخش عمومی میتونیم اطلاعات نظیر تغییر شماره تلفن همراه،انتخاب پروفایل ، تغییر نام و نام خانوادگی و اضافه کردن تاریخ تولد(در همه میزکارهایی که عضو هستید، همکارانتان در روز تولد شما باخبر می‌شوند.)
In the general section, we can change information such as changing mobile phone number, selecting profile, changing first and last name and adding date of birth (in all desks where you are a member, your colleagues will be informed on your birthday.)
![Screenshot 2024-09-24 164545](https://github.com/user-attachments/assets/1381c74a-9b02-44a3-82ea-af8f68762821)

در بخش امنیت  میتوانیم نشست های فعال رو مشاهده بکنیم زمان ورود و خروج کاربر و همچنین اطلاعات نظیر آیپی کاربر، سیتسم عامل،مرورگر و همچنین تعداد تلاش های موفق و ناموفق رو نیز نشون میده این قابلیت ها خیلی خوبه و امنیت نرم افزار رو بالا میبره 
In the security section, we can see the active devices, the user's login and logout time, as well as information such as the user's IP address, operating system, browser, as well as the number of successful and unsuccessful attempts. These features are very good and increase the security of the software.
![Screenshot 2024-09-24 165040](https://github.com/user-attachments/assets/6e0f9e00-7866-4507-af68-1151e716593f)

و در بخش نوتیفیکیش یا ایمیل میتوانیم ایمیلی را برای دریافت نوتیفیکیشن وارد کنیم این بخش مخصوص برای کاربرانی که سیستم عامل  موبایل آن ها IOS است طراحی شده است تا ان ها نیز از طریق ایمیل پیام های مرتبط را دریافت کنند 
And in the notification or e-mail section, we can enter an e-mail to receive the notification. This section is specially designed for users whose mobile operating system is IOS, so that they can also receive relevant messages through e-mail.
![Screenshot 2024-09-24 165418](https://github.com/user-attachments/assets/8b39a2b7-6e33-421d-82dd-52805e57f246)
 
___
