### ISSUE TITLE
Research vendor applications' UI: Trello, ClickUp, Monday, and GitHub Projects

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#14]
**[EN]**  
Sign up in these applications:
1. Trello
2. ClickUp
3. Monday
4. GitHub Projects

and try using them and exploring their features. As you are using these pieces of software, try taking notes about their:
- UI
- UX
- Flows of Processes
- Systems (the app might be able to be broken in multiple logical parts: e.g. task management, messaging, financial features). Each application might have different systems and features e.g. In GitHub you can reference an `issue` or `pull request` or parts of codebase in a task which is not available in most other applications. 
- Features of each logical part (e.g. features available in task management)
- Terminology

---

**[FA]**
در برنامه‌های زیر ثبت نام کن:
1. Trello
2. ClickUp
3. Monday
4. GitHub Projects

و اونارو به عنوان کسی که میخواد پروژه رو مدیریت کنه استفاده کن تا بتونی امکاناتی که برنامه در اختیار مدیر پروژه قرار میده رو ببینی و اکتشاف کنی. سعی کن وقتی داری استفاده میکنی موارد زیر رو یادداشت کنی:
1. یو آی
2. یو ایکس
3. اینکه جریان کلی روندها توی برنامه چطوریه (مثلا ثبت نام کردی بعدش چی شد، یا پروژه ایجاد کردی بعدش چی شد)
4. سیستم‌های متفاوت رو تشخیص بده. اکثر برنامه‌هایی که مشخص شده، دارای بخش‌های متفاوتی هستن. مثلا ممکنه یکی مدیریت تسک + حسابداری + پیام‌رسانی داشته باشه، ممکنه یکی دیگه مدیریت تسک + مدیریت پروژه داشته باشه. هر تقسیم بندی‌ای که به نظرتون منطقی اومد رو بنویسید.
5. برای هر بخش که تو مورد قبلی مشخص کردیم باید تمام فیچرهاشو در بیاریم و مستند کنیم.
6. ترمینولوژی (واژگان مورد استفاده)

**Comment by ElaheSalahi** [comment]
# ClickUp
* **Hover Effects**: When hovering over buttons, each one triggers a different action, disrupting consistency.
* **White Space Usage**: The platform makes good use of white space. The logo consists of yellow, pink, blue, and purple colors. The frequent use of purple and pink throughout the interface adds to its visual appeal. Overall, the color combination has been applied effectively.
* **Customization Options**: Users can personalize their dashboards and views according to their needs, such as Table, Calendar, etc.
* **Third-Party Integrations**: A key advantage is the ability to connect Google Drive, Slack, and more, eliminating the need to switch between apps.
* **Navigation Design**: Menus are designed to allow users to easily switch between different sections.
* **Keyboard Shortcuts**: The platform supports using keyboard shortcuts for efficient task handling.
* **Font Weights**: A wide variety of font weights is used, with the CTA button utilizing the Regular weight.
* **Mobile Version Issues**:
    * The button sizes in the mobile version are quite large.
    * The login option isn’t displayed on the main page; users need to access the menu to find it.
    * The mobile responsive design has some issues and is not well-optimized.
* **UI Complexity**: One challenge with ClickUp is that it may appear cluttered, especially to beginners or users seeking simplicity. When dealing with a large number of projects, the user interface can become very complex and information-heavy.
* **Team Collaboration**: Teams can easily access file sharing and chats.
* **Learning Curve**: Due to the wide range of features, users may require more time to get familiar with the system.
* **Mobile Display Issues**: The right side of the page is not fully visible in the mobile version. For example, buttons and texts are not properly aligned, indicating a responsiveness issue.
* **Oversized Elements**: Certain elements, such as the "Project Update" and "Summarize List" buttons, are disproportionately large and occupy too much space in the small mobile view.
* **Task Communication**: The platform allows sending messages and leaving comments on tasks to enhance team communication.
* **Task Status**: Users can mark task status as To Do, In Progress, or Done.

# Trello
* **Simple Design and Bright Colors**: The platform features a simple design with the use of bright colors on cards and labels, allowing users to start working without needing special training.
* **Drag and Drop Functionality**: Users can easily drag and drop cards between lists, enabling quicker task management.
* **Customizable Board Backgrounds**: Users have the ability to change board backgrounds to their liking.
* **Card Organization**: Cards are organized in a straightforward way, displaying all key information like descriptions, due dates, labels, and more in one place.
* **Scrolling Issue**: If there are too many cards and lists, users may need to scroll extensively, which can cause confusion and difficulty.
* **User-Friendliness for All Levels**: Whether the user is a beginner or an expert, they can easily create new boards and manage tasks.
* **Butler Automation Tool**: Users can automate repetitive processes with the Butler tool, improving productivity.
* **Lack of Advanced Tools for Larger Teams**: For larger teams or projects requiring complex reporting and resource management, the default tools may not be sufficient.
* **Managing Multiple Boards**: When there are many boards, navigating and managing them can become challenging.
* **Collaboration Features**: Team members can be invited to boards and tasks can be assigned to them.
* **Mobile Version Limitations**: Due to display limitations on mobile devices, information is displayed more compactly, leading to increased scrolling and reduced quick access to information.
* **Real-Time Sync**: All changes made on the mobile version are quickly synced with the web version and other devices, allowing users to work seamlessly from anywhere.

# Monday
* **Color-Coded Task Status**: Different colors are used for task statuses like Done, In Progress, and Stuck, which helps in organizing and prioritizing tasks effectively.
* **Use of Clear Animations and Icons**: The use of animations and clear icons throughout the interface makes the user experience simple and engaging.
* **Accessible Sidebar Menu**: The sidebar provides easy access to key sections such as projects, dashboards, and reports.
* **Clear Buttons and Links**: Buttons and links are clearly defined and appropriately sized, helping users complete their desired tasks effortlessly.
* **Easy Creation of Boards and Tables**: Users can easily create boards, tables, and tasks. They can choose from pre-set templates or personalize them as needed.
* **Flexible Data Views**: Users can view their information and data in various formats such as tables, calendars, Gantt charts, etc., allowing them to monitor their projects and tasks effectively.
* **Drag & Drop Functionality**: This feature allows users to easily move columns, cards, and tasks, enabling them to make changes with ease.
* **Real-Time Notifications**: Users can quickly notice critical updates through notifications, staying informed about the status of their projects.
* **Initial Learning Curve**: Despite its attractive design, new users might experience some confusion initially and may need more time to get familiar with all the features.

# GitHub
* **Standard and Clear Color Usage**: GitHub uses different, standardized colors that help make texts and elements easily distinguishable and readable.
* **Effective Use of White Space**: With well-utilized white space, clear sidebars, and defined headers, users can easily navigate the site.
* **Consistent Design Patterns**: All GitHub pages follow a consistent design pattern, creating a sense of familiarity and uniformity for users.
* **Clear Display of Key Information**: On each page, critical information and main buttons are clearly highlighted, enabling users to easily find what they need.
* **Effective Feedback**: The platform effectively displays error messages and success notifications to users.
* **Overwhelming for New Users**: New users might find the numerous options and features overwhelming.
* **Complex Settings**: Extensive and complex settings might present challenges and confusion for newcomers.
* **Readable Fonts**: GitHub uses readable fonts with appropriate sizes for displaying code, descriptions, and texts, making it easier for users to read and review code.
* **Familiar Icons**: The platform employs simple and familiar icons, making it easier for users to understand the functions quickly.
* **Efficient Project Management**: GitHub provides simple and efficient project management, allowing users to create, update, and manage repositories with ease.
* **Potential Confusion with Advanced Features**: Despite its simple design, new users might find it confusing to use some advanced features.
* **Git Knowledge Required**: To make optimal use of GitHub, users need to be familiar with Git commands, which could be a challenge for beginners.
