### ISSUE TITLE
Research Vendor applications: Trello, GitHub Projects, MS Project, and BaseCamp

### ISSUE THREAD

**Issue by atareversei** [basliqlabs/qwest-docs#7]
**[EN]**  
Sign up in these applications:
1. Trello
2. GitHub Projects
3. MS Projects
4. BaseCamp

and try using them and exploring their features. As you are using these pieces of software, try taking notes about their:
- UI
- UX
- Flows of Processes
- Systems (the app might be able to be broken in multiple logical parts: e.g. task management, messaging, financial features). Each application might have different systems and features e.g. In GitHub you can reference an `issue` or `pull request` or parts of codebase in a task which is not available in most other applications. 
- Features of each logical part (e.g. features available in task management)
- Terminology

---

**[FA]**
در برنامه‌های زیر ثبت نام کن:
1. Trello
2. GitHub Projects
3. MS Projects
4. BaseCamp

و اونارو به عنوان کسی که میخواد پروژه رو مدیریت کنه استفاده کن تا بتونی امکاناتی که برنامه در اختیار مدیر پروژه قرار میده رو ببینی و اکتشاف کنی. سعی کن وقتی داری استفاده میکنی موارد زیر رو یادداشت کنی:
1. یو آی
2. یو ایکس
3. اینکه جریان کلی روندها توی برنامه چطوریه (مثلا ثبت نام کردی بعدش چی شد، یا پروژه ایجاد کردی بعدش چی شد)
4. سیستم‌های متفاوت رو تشخیص بده. اکثر برنامه‌هایی که مشخص شده، دارای بخش‌های متفاوتی هستن. مثلا ممکنه یکی مدیریت تسک + حسابداری + پیام‌رسانی داشته باشه، ممکنه یکی دیگه مدیریت تسک + مدیریت پروژه داشته باشه. هر تقسیم بندی‌ای که به نظرتون منطقی اومد رو بنویسید.
5. برای هر بخش که تو مورد قبلی مشخص کردیم باید تمام فیچرهاشو در بیاریم و مستند کنیم.
6. ترمینولوژی (واژگان مورد استفاده)

**Comment by thisis-mahyar** [comment]
# BaseCamp
Basecamp is an efficient collaboration tool used by thousands of teams worldwide. Teams use Basecamp to track assignments, collaborate on documents, plan projects, chat, and more.

The sentence below is what Basecamp says about itself:

> Basecamp is the project management platform that helps small teams move faster and achieve more than they ever thought possible.

**Comment by thisis-mahyar** [comment]
# GitHub Projects

## User Interface

- GitHub Projects is just one of the many features provided by GitHub, and its interface follows GitHub’s standard UI. GitHub has a simple and intuitive design that enhances user interaction. I also use GitHub's dark theme in my IDEs.

- The default theme is dark, and many developers prefer it over the light theme. I like the shade of black used here, which is not completely black.

- You can see this type of UI on other platforms like Trello, LeetCode, GitHub, and Stack Overflow.

    <img src="https://github.com/user-attachments/assets/ba44b61e-dac6-45ce-9a30-7c9d8f1da3e3" width = 600>

## User Experience

- When it comes to complex apps, simplicity plays a major role, and GitHub handles this quite well! The app is easy to navigate and use.

- As I mentioned before, projects are treated as a section alongside others like Repositories. This means you shouldn't expect it to function as a standalone, full-scale project management app. It may only meet the basic needs of your project. So, if you have a large organization, I recommend using other dedicated apps.

- However, one great feature is that you can manage your project within GitHub’s environment, giving you full access to your projects as well as other sections like issues, pull requests, repositories, and more.

- And the main purpose of GitHub Projects is handling your issues and pull requests. As it is said in the documentation: ... A project integrates with your issues and pull requests on GitHub ...

## Flows and Processes

### 1. How to sign up?

You don't need to sign up if you’ve already signed into GitHub.
Otherwise, if you don't have any GitHub account:
1. Go to [GitHub's official website](https://github.com/).
2. In the main page, click on the **Sign up** button.
3. Enter your Email and password and username.
4. Tick the checkBox if you want to receive updates and announcements from GitHub (optional).
5. Verify that you're not a robot!
6. Enter the code that is sent to your Email via GitHub.

Now, you've been signed up to GitHub. But there are a few things left!
1. How many members will be working with you?
2. Are you a student or teacher?
3. What are your interests?
4. Do you want to use GitHub pro or do you want to continue with your free account?

Welcome to GitHub!

### 2. How to create the project?

You can either create an organization project or a user project.

To create an organization project:
1. In the upper-right corner of GitHub, select your profile photo, then click  Your organizations.
2. Click the name of your organization.
3. Under your organization name, click **Projects**.
4. Click **New project**.

To create a user project:
1. In the top right corner of GitHub, click your profile photo, then click Your profile.
2. On your profile, click **Projects**.
3. Click **New project**.

### 3. What are templates?

After creating the project (for both types), a pop-up window will appear, suggesting you to use templates (depending on your own needs). There are 8 templates:

Template | Description | Content
:- | :- | :-
Team planning | Manage your team's work items, plan upcoming cycles, and understand team capacity | Backlog, Team capacity, Current Iteration, Roadmap, My Items
Feature release | Manage your team's prioritized work items when planning for a feature release 🚀 | Prioritized backlog, Status board, Roadmap, Bugs🐛, In review, My items
Kanban | Visualize the status of your project and limit work in progress | Backlog, Priority board, Team items, Roadmap, In review, My items
Bug tracker | Track and triage your bugs 🐛 | Prioritized bugs, Triage, In review, My items
Iterative development | Plan your current and upcoming iterations as you work through your prioritized backlog of items | Current iteration, Next Iteration, Prioritized backlog, Roadmap, In review, My items
Product launch | Manage work items across teams and functions when planning for a product launch 🚀 | Prioritized backlog, Status board, Current iteration, Roadmap, Bugs🐛, My items
Roadmap | Manage your team's long term plans as you plan out your roadmap | Monthly roadmap, Quarterly roadmap, Backlog
Team retrospective | Reflect as a team what went well, what can be improved next time, and action items | Retrospective, Categorize feedback, Action items

For the beginning, it can be better to create the project from scratch rather than the templates. The templates are designed for more professional users who have a better insight and knowledge about project managements. You can select Table, Board or Roadmap to create the project from scratch.

### 4. Inside of the Project

Now, here we have our raw project! A project consist of views. A view is something that holds your project's info and can have 3 types of layouts:

- **Table layout:** is a spreadsheet that conatains your issues, pull requests, and draft issues with metadata from GitHub and the custom fields you've added to your project.

    <img src = "https://github.com/user-attachments/assets/6839f93c-63c9-47d4-ad12-04428a17b49a">
    
- **Board layout:** this layout spreads your items (issues, pull requests, etc.) across customizable columns. You can set other names to your columns, but I recommend you to set them as if they show the status of the project. Because, you can also drag them items from column to column, so, it is better to organize them as if each of the items are in a certain stage in your project and the stage will be changed.

    <img src = "https://github.com/user-attachments/assets/2215a2ea-cfbf-4c97-bbf5-6e12b01b19f3">

- **Roadmap layout:** this layout concentrates on time and deadlines of your project. First you have to add 2 Date fields. One shows the start time and the other one shows the end time of your project. Then on the table, in front of each item, you can click inside the board and drag it to your desired date. This time period will be the time you have to finish your item.

<img src="https://github.com/user-attachments/assets/d89b5c92-6e62-45c9-b730-e0ab2854fb40">

### Dive Deeper!
#### Add item
To add an item to your view, click the **+** icon at the bottom of your list of items. Here, you have 3 options:

Option | Description
:- | :-
Craete a draft issue | If you start to type your item, it will be considered as a draft issue. You can then convert this to an issue.
Create a new issue | you can create a new issue from scratch.
Add item from repository | you can add issues from your selected repository

<img src="https://github.com/user-attachments/assets/dd8be164-80cb-428b-acb5-f654e88b16ae" width=300>

## Systems and features

### You can set description and README to you project!
1. In the top-right of your project page, click the icon circled in the picture below.

    <img src="https://github.com/user-attachments/assets/447b8f33-e748-4ba8-9f33-70a000a52337" width=250/>

2. Here you can write a short description and a README to your project.
3. To save changes to your README, click Save.

### You can make a copy of your project
1. Go to your project's setting by tapping the icon below.

    <img src = "https://github.com/user-attachments/assets/28505ac8-40f5-4885-babd-7513822fcea4" width = 500>

3. Here, you can also set a description and a README to your project. But down below, you have a option to copy your project.
4. By copying your project, views, custom fields, insights, and workflows will be copied. But issues and pull requests will not be copied to the other project. But you have an option to copy draft issues.
5. Select the owner of your new project.
6. Set a name to your new project.

### Other options in your project setting page
- At the bottom of your project setting page, you can change the visibility to public so that everyone can see your project.
- You can also close or delete your project just in the field where project visibility stands. But be careful, this is the danger zone!
- You can invite collaborators to your project. On the left side of your project setting page, go to **Manage Access** and click the green button to invite the collaborators.
- You can also add custom field from here! Just right the **Custom Fields** tab!

### You can filter your project list
Wheter you are in your profile project or your organization projects, you can find your specific project by typing inside the searchbar.
The syntax below helps you to find your projects:

Qualifier | Explanation
:- | :-
`is:open` | Returns projects that are currently open.
`is:closed` | Returns projects that are currently closed.
`is:template` | Returns projects that are marked as a template.
`is:private` | Returns projects are set to private visibility.
`is:public` | Returns projects are set to public visibility.
`creator:USERNAME` | Returns projects created by USERNAME.
`sort:title-asc` | Sort by project title.
`sort:updated-asc` | Sort by when the project was last updated.
`sort:created-asc` | Sort by when the project was created.

## Key words

Word | Description               
:- | :-                       
Issues | Issues are items you can create in a repository to plan, discuss and track work
Pull Request | When a developer is ready to merge new code changes with the main project repository
Kanban board | An agile project management tool designed to help visualize work, limit work-in-progress, and maximize efficiency (or flow).
Triage | A technique for prioritizing  problems
Backlog | Uncompleted work
Retrospective | Looking back on or dealing with past events or situations
Agenda | A list of items to be discussed at a formal meeting





- Information is synced automatically to your project as you make changes, updating your views and charts. This integration works both ways
